# Generated by Django 5.2.4 on 2025-08-13 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_remove_blogpost_attachments_blogpost_attachements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='slug',
        ),
    ]
